let express = require('express');
let app = express();

app.listen(8080);
let list = [
    {
        img:'https://raw.githubusercontent.com/HL1115/webpack/master/src/assets/imgs/list1.png',
        text:'目的地'
    },
    {
        img:'https://raw.githubusercontent.com/HL1115/webpack/master/src/assets/imgs/list1.png',
        text:'亲子游学'
    },
    {
        img:'https://raw.githubusercontent.com/HL1115/webpack/master/src/assets/imgs/list1.png',
        text:'酒店预订'
    },
    {
        img:'https://raw.githubusercontent.com/HL1115/webpack/master/src/assets/imgs/list1.png',
        text:'车辆接送'
    },
    {
        img:'https://raw.githubusercontent.com/HL1115/webpack/master/src/assets/imgs/list1.png',
        text:'签证代办'
    },
    {
        img:'https://raw.githubusercontent.com/HL1115/webpack/master/src/assets/imgs/list1.png',
        text:'精彩瞬间'
    }
]
let theme = [
    {
        type:0,
        tit:'意大利塞浦路斯+马耳他+西西里岛10晚13天'
    },
    {
        type:0,
        tit:'意他+西西里晚13天'
    },
    {
        type:0,
        tit:'意大利塞西西里3天'
    },
    {
        type:1,
        tit:'意大利7'
    },
    {
        type:1,
        tit:'意大利6'
    },
    {
        type:2,
        tit:'意大5'
    },
    {
        type:2,
        tit:'意2'
    },
    {
        type:2,
        tit:'塞3'
    },
    {
        type:2,
        tit:'意大4'
    },
]
app.get('/api/list',(req,res)=>{
    res.json(list);
})
app.get('/api/nav',(req,res)=>{
    console.log(req.query);
    let arr = theme.filter((item)=>req.query.id==item.type)
    res.json(arr);
})